name: Security Compliance Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # CodeQL
  codeql:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Set up JDK 1.11
      if: matrix.language == 'java'
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Build with Maven
      if: matrix.language == 'java'
      run: mvn -B package --file pom.xml

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1


  # Run a number of Open Source tools
  ossar:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Run OSSAR
      uses: github/ossar-action@v1
      id: ossar

    - name: Upload OSSAR results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}


  # Compliance check
  compliance:
    runs-on: ubuntu-latest

    needs: [ codeql, ossar ]

    steps:
    - name: Advance Security Compliance Action
      uses: GeekMasher/advanced-security-compliance@1.1
      with:
        token: ${{ secrets.OCTODEMOBOT_SECURITY_AND_SOFTWARE_COMPOSITION_TOKEN }}
        policy: octodemo/ghas-policy
        policy-path: policies/conditions.yml
